name: Marp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Marp Build
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
            args: main.md -o build/main.pptx
        env:
          MARP_USER: root:root
