name: Marp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Marp Build
      uses: docker://marpteam/marp-cli:latest
      with:
        args: main.md --pptx
      env:
        MARP_USER: root:root
    - uses: actions/upload-artifact@v2
      with:
          name: output_slide
          path: main.pptx
